services:
  web:
    restart: always
    build: 
      context: ./app
      dockerfile: Dockerfile-prod-final
    command: gunicorn donald_project.wsgi:application --bind 0.0.0.0:8000
    # command: python manage.py runserver 0.0.0.0:8000
    # 0.0.0.0 is any port django exposes. 8000 is the machine port
    # (i.e., port user mentions in the browser if they are not using nginx/docker)
    volumes: 
      # - ./app/:/usr/src/app/ # useful only diring development
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env-prod
    depends_on:
      - db
   
  db:
    restart: always
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env-prod-db
    ports:
      - 5432:5432
  nginx:
    restart: always
    build: ./nginx
    # the port is not needed in production because the loadbalancer
    # resolves it
    ports:  
     - 1337:80
    depends_on:
      - web
    volumes:
      - static_volume:/usr/share/nginx/html/static 
      
volumes:
  postgres_data:
  static_volume:

# I pushed but it failed to trigger actions (1)
